### ISSUE TITLE
Dataset in CoronaWhy Dataverse 

### ISSUE THREAD

**Issue by geek80** [bfarago/hu_covid_datas#1]
Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/ZA9QPR

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by bfarago** [comment]
hi
sure. 
In case of there are some (better) format, or shall I change/adapt to be compatible to other format, please discuss the topic, then I can update / fix the field names, etc...
I am not the researcher of the data, the original publisher. There is a link to the referenced source in the description. My source refreshing daily, I update csv files a little less often. 
I will take a look on the metadata topic soon, in case you have a suggestion about a document or what should I read regarding the above question, please tell me.

**Comment by geek80** [comment]
Great, thank you. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the Dataset creator permissions to your dataset. Then please add relevant metadata - description and keywords to your dataset.

**Comment by bfarago** [comment]
done. The uname is the same as here..

**Comment by geek80** [comment]
Thanks author permissions have been assigned to you. Here is an sample dataset as an example.
https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TZMOTL 

And intro docs on metadata and principles of linked data like

https://www.europeandataportal.eu/sites/default/files/d2.1.2_training_module_1.4_introduction_to_metadata_management_en_edp.pdf

https://www.slideshare.net/OpenDataSupport/linked-open-data-principles-technologies-and-examples
